#!/bin/bash
../../dfu-util/src/dfu-util -a 1 -d 0x1d50:0x5119 -D u-boot.udfu
if [ $? -eq 1 ] ; then
../../dfu-util/src/dfu-util -a 1 -d 0x1d50:0x5120 -D u-boot.udfu
../../dfu-util/src/dfu-util -a 1 -d 0x1d50:0x5119 -D u-boot.udfu
fi

